@startuml
'https://plantuml.com/state-diagram
hide empty description
'scale 350 width

[*] --> ConnectionWait
ConnectionWait --> SendGreeting : accept()
SendGreeting --> LoginWait : TextMsg>

LoginWait --> CheckLogin : >LoginMsg
LoginWait --> SendGreeting : >all other msgs
CheckLogin --> SendLoginConfirm : valid
SendLoginConfirm --> CmdWait : TextMsg>
CheckLogin --> SendLoginFail : invalid
SendLoginFail --> SendGreeting : TextMsg>

CmdWait -up-> SayGoodbye : >LogoutMsg
SayGoodbye -up-> ConnectionWait : TextMsg>

CmdWait --> BuildHelpReply : >HelpMsg
CmdWait --> BuildUserListReply : >ListUsersMsg
CmdWait --> SetOption : >OptionMsg w/ setting
CmdWait --> BuildOptionReply : >OptionMsg w/o setting
SetOption --> BuildOptionReply

''''''''''
CmdWait --> SaveFile : >FileMsg
SaveFile --> BuildSaveOKReply
SaveFile --> BuildSaveFailReply
BuildSaveOKReply --> SendTextReply
BuildSaveFailReply --> SendTextReply
''''''''''
CmdWait --> BuildEchoReply : >TextMsg
BuildHelpReply --> SendTextReply
BuildUserListReply --> SendTextReply
BuildOptionReply --> SendTextReply
BuildEchoReply --> SendTextReply

SendTextReply --> CmdWait : TextMsg>

@enduml